title: Semantica Documentation
description: Open Source Framework for Semantic Intelligence & Knowledge Engineering
theme: jekyll-theme-minimal
logo: /semantica_logo.png
show_downloads: false
github:
  repository_url: https://github.com/Hawksight-AI/semantica
  repository_name: Hawksight-AI/semantica

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference: api.md
  - Examples: examples.md

